### ISSUE TITLE
Alternate "slim" version of empower.

### ISSUE THREAD

**Issue by jamestalmage** [power-assert-js/empower#20]
@twada 

Poking through the code, I think there is room for a "slim" version of empower.

If my understanding is correct, then the following:

```
saveContextOnRethrow: true,
modifyMessageOnRethrow: false
```

Does not require a formatter at all. It just attaches the context and re-throws a copy.

In the "slim" version I am picturing, it would only take a patterns argument.

Also, instead of re-throwing an error (which messes with the existing stack trace needlessly). You could just use [`serialize-error`](https://github.com/sindresorhus/serialize-error) attach the context, and throw.

We would format and print the message on the main thread using `powerAssertContext`.

Is what I am saying making sense?

**Comment by twada** [comment]
@jamestalmage Yeah, [that's exactly what I'm thinking of](https://github.com/twada/empower-assert/pull/1).

**Comment by twada** [comment]
Let me explain a history behind the code.

> Also, instead of re-throwing an error (which messes with the existing stack trace needlessly). You could just use serialize-error attach the context, and throw.

I've implemented the same strategy, but some of old browsers (including PhantomJS) have strange behavior. When I rethrow Errors after attaching some props, the props disappear.

```js
try {
    try {
        ...
    } catch (e) {
        e.foo = 'bar';
        throw e;
    }
} catch (e) {
    assert(e.foo === 'bar');  // Error on old PhantomJS
}
```

[refactor(empower): always re-instantiate AssertionError on rethrow · power-assert-js/empower@997da24](https://github.com/power-assert-js/empower/commit/997da242ebbd14f8340997a08bf78477ed1c2a7f)

However, I found that the attached props are remaining on current PhantomJS.
So I can just attach and rethrow the original Error now.

It's a delightful discovery. Thanks!

**Comment by jamestalmage** [comment]
@twada - `serialize-error` actually does not create an error. It creates a plain old javascript object with deep copies of the Errors properties. An Error object does not survive `JSON.stringify()` very well. Especially assertion errors that have circular references.

Check the [unit tests](https://github.com/sindresorhus/serialize-error/blob/master/test.js) for all it does.

For use outside AVA, throwing non-errors is probably a bad idea. Could you maybe split most of the functionality into another module? `empower-core` or something. It should take a `copyAssertion` callback. `empower` can continue to copy the Assertion the way you've been doing it here, and we can make a custom version that uses `serialize-error` to make the copy.

**Comment by twada** [comment]
@jamestalmage 

> Could you maybe split most of the functionality into another module? empower-core or something. It should take a copyAssertion callback.

Yeah [I'm working on that](https://github.com/twada/empower-assert/pull/1) !

**Comment by twada** [comment]
Update: Now [in a beta stage](https://github.com/twada/empower-core)

**Comment by twada** [comment]
Close this issue since [twada/empower-core](https://github.com/twada/empower-core) is going on.
